name: Deploy hexo blog
on:
  push:
    branches:
      - "hexo"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "hexo"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "10.24.1"
          registry-url: https://registry.npmjs.org/

      - name: Check yarn & node version
        run: |
          echo "Node version is `node -v`"
          echo "Yarn version is `npm -v`"

      - name: Build & Deploy
        run: |
          npm config set registry https://registry.npm.taobao.org
          npm install -g hexo-cli
          npm install
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          sed -i'' "s~git@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml
          rm -rf .deploy_git
          hexo clean
          hexo build
          hexo deploy